/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleClaimsRouteImport } from './routes/$locale/claims'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleFaqRouteImport } from './routes/$locale/faq'
import { Route as LocaleQuoteRouteImport } from './routes/$locale/quote'
import { Route as LocaleSolutionsIndexRouteImport } from './routes/$locale/solutions/index'
import { Route as LocaleSolutionsSlugRouteImport } from './routes/$locale/solutions/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleClaimsRoute = LocaleClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleQuoteRoute = LocaleQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSolutionsIndexRoute = LocaleSolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSolutionsSlugRoute = LocaleSolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/claims': typeof LocaleClaimsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/solutions/$slug': typeof LocaleSolutionsSlugRoute
  '/$locale/solutions/': typeof LocaleSolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/claims': typeof LocaleClaimsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/solutions/$slug': typeof LocaleSolutionsSlugRoute
  '/$locale/solutions': typeof LocaleSolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/claims': typeof LocaleClaimsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/solutions/$slug': typeof LocaleSolutionsSlugRoute
  '/$locale/solutions/': typeof LocaleSolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/claims'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/quote'
    | '/$locale/'
    | '/$locale/solutions/$slug'
    | '/$locale/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/claims'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/quote'
    | '/$locale'
    | '/$locale/solutions/$slug'
    | '/$locale/solutions'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/claims'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/quote'
    | '/$locale/'
    | '/$locale/solutions/$slug'
    | '/$locale/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/claims': {
      id: '/$locale/claims'
      path: '/claims'
      fullPath: '/$locale/claims'
      preLoaderRoute: typeof LocaleClaimsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/quote': {
      id: '/$locale/quote'
      path: '/quote'
      fullPath: '/$locale/quote'
      preLoaderRoute: typeof LocaleQuoteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/solutions/': {
      id: '/$locale/solutions/'
      path: '/solutions'
      fullPath: '/$locale/solutions/'
      preLoaderRoute: typeof LocaleSolutionsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/solutions/$slug': {
      id: '/$locale/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/$locale/solutions/$slug'
      preLoaderRoute: typeof LocaleSolutionsSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleClaimsRoute: typeof LocaleClaimsRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleQuoteRoute: typeof LocaleQuoteRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleSolutionsSlugRoute: typeof LocaleSolutionsSlugRoute
  LocaleSolutionsIndexRoute: typeof LocaleSolutionsIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleClaimsRoute: LocaleClaimsRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleQuoteRoute: LocaleQuoteRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleSolutionsSlugRoute: LocaleSolutionsSlugRoute,
  LocaleSolutionsIndexRoute: LocaleSolutionsIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
